"""Generated figures gallery."""
from __future__ import annotations

import streamlit as st

from pipeline.data_pipeline import available_figures


def render_figures() -> None:
    st.title("Generated Figures")
    st.caption("Figures are generated by repository scripts, not by the dashboard.")
    figures = available_figures()
    if not figures:
        st.info("No PNG figures found. Run scripts/make_figures.py.")
        return

    for i in range(0, len(figures), 2):
        cols = st.columns(2)
        for col, fig in zip(cols, figures[i : i + 2]):
            col.image(str(fig), caption=fig.name, use_container_width=True)

