"""SQLite research queries for the PM2.5 forecasting research questions.

This script exists for the DAP391m "SQL queries linked to RQ" requirement.
The modelling pipeline primarily uses pandas, but the completed result CSVs
are also loaded into a local SQLite database so the same evidence can be shown
as explicit SQL SELECT / GROUP BY / JOIN queries.

Outputs:
    results/pm25_research_queries.sqlite
    results/sql_rq1_model_ranking.csv
    results/sql_rq2_hybrid_effectiveness.csv
    results/sql_rq3_common_history_sensitivity.csv
"""

from __future__ import annotations

import sqlite3
from pathlib import Path

import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "results"
DB_PATH = RESULTS / "pm25_research_queries.sqlite"


def load_table(conn: sqlite3.Connection, csv_name: str, table_name: str) -> None:
    """Load one generated experiment CSV into SQLite."""
    path = RESULTS / csv_name
    if not path.exists():
        raise FileNotFoundError(f"Missing required result file: {path}")
    frame = pd.read_csv(path)
    frame.to_sql(table_name, conn, if_exists="replace", index=False)


def run_query(conn: sqlite3.Connection, sql: str, output_name: str) -> pd.DataFrame:
    """Execute a SQL query, print it, and export the result for screenshots."""
    print("\n" + "=" * 88)
    print(output_name)
    print("-" * 88)
    print(sql.strip())
    print("-" * 88)
    frame = pd.read_sql_query(sql, conn)
    print(frame.to_string(index=False))
    frame.to_csv(RESULTS / output_name, index=False)
    return frame


def main() -> None:
    RESULTS.mkdir(exist_ok=True)
    if DB_PATH.exists():
        DB_PATH.unlink()

    with sqlite3.connect(DB_PATH) as conn:
        # Source tables generated by the training/evaluation pipeline.
        load_table(conn, "multistation_seed_metrics.csv", "seed_metrics")
        load_table(conn, "station_effectiveness.csv", "station_effectiveness")
        load_table(
            conn,
            "history_sensitivity_hybrid.csv",
            "history_sensitivity_hybrid",
        )

        # RQ1: Which model forecasts hourly PM2.5 most accurately?
        # This query aggregates MAE over stations and seeds, then ranks models
        # within each forecast horizon. Lower MAE is better.
        rq1_sql = """
        WITH model_horizon AS (
            SELECT
                model,
                horizon,
                AVG(MAE) AS mean_mae,
                AVG(RMSE) AS mean_rmse,
                AVG(sMAPE) AS mean_smape,
                COUNT(*) AS n_rows
            FROM seed_metrics
            GROUP BY model, horizon
        ),
        ranked AS (
            SELECT
                *,
                RANK() OVER (
                    PARTITION BY horizon
                    ORDER BY mean_mae ASC
                ) AS mae_rank
            FROM model_horizon
        )
        SELECT
            horizon,
            model,
            ROUND(mean_mae, 3) AS mean_mae,
            ROUND(mean_rmse, 3) AS mean_rmse,
            ROUND(mean_smape, 3) AS mean_smape,
            n_rows,
            mae_rank
        FROM ranked
        WHERE mae_rank <= 3
        ORDER BY horizon, mae_rank, model;
        """
        run_query(conn, rq1_sql, "sql_rq1_model_ranking.csv")

        # RQ2: Does the gated TimeMixer-XGBoost hybrid beat the strongest
        # non-hybrid comparator at each station and horizon?
        # mae_gap_percent_vs_best is easier to present than a negative improvement score.
        # Positive values mean the hybrid is worse than the strongest comparator.
        rq2_sql = """
        SELECT
            station_id,
            site_type,
            horizon,
            best_comparator,
            ROUND(comparator_mae, 3) AS comparator_mae,
            ROUND(hybrid_mae, 3) AS hybrid_mae,
            ROUND(mae_delta, 3) AS mae_delta,
            ROUND(-improvement_percent, 2) AS mae_gap_percent_vs_best,
            hybrid_wins
        FROM station_effectiveness
        ORDER BY station_id, horizon;
        """
        run_query(conn, rq2_sql, "sql_rq2_hybrid_effectiveness.csv")

        # RQ3: Does the conclusion change when every station uses the same
        # 2021-start historical period?
        # A small delta means the unequal-history concern does not reverse the
        # conclusion. Negative delta means common-history improved MAE.
        rq3_sql = """
        SELECT
            station_id,
            horizon,
            ROUND(MAE_available_history, 3) AS mae_available_history,
            ROUND(MAE_common_2021, 3) AS mae_common_2021,
            ROUND(MAE_delta_common_minus_available, 3) AS delta_mae,
            CASE
                WHEN MAE_delta_common_minus_available < 0 THEN 'common_2021_better'
                WHEN MAE_delta_common_minus_available > 0 THEN 'available_history_better'
                ELSE 'tie'
            END AS sensitivity_result
        FROM history_sensitivity_hybrid
        ORDER BY station_id, horizon;
        """
        run_query(conn, rq3_sql, "sql_rq3_common_history_sensitivity.csv")

    print("\nSQLite database written to:", DB_PATH)


if __name__ == "__main__":
    main()
